src: add -n flag to create new repo

diff --git a/bin/src b/bin/src
--- a/bin/src
+++ b/bin/src
@@ -27,31 +27,35 @@ open_tmux_window() {
 
 SHOULD_OPEN_TMUX_WINDOW=false
 NEW_REPO=false
+REPO_EXPRESSION=""
 
-while getopts ":t:n" OPT; do
+while getopts ":tnd" OPT; do
 	case $OPT in
 		t)
 			SHOULD_OPEN_TMUX_WINDOW=true
-			shift
 			;;
 		n)
 			NEW_REPO=true
-			shift
 			;;
-		\?)
-			die "Invalid option -$OPTARG"
+		d)
+			DEBUG=YES
 			;;
 	esac
 done
 
-[ -z "$1" ] && {
-	die "usage: $BIN github.com/<user>/<repo>"
+shift $(( OPTIND - 1 ))
+
+REPO_EXPRESSION="$1"
+
+[[ -z "$REPO_EXPRESSION" ]] && {
+	debug "REPO_EXPRESSION: $REPO_EXPRESSION"
+	die "usage: $BIN [-d] [-t] [-n] [github.com/[<user>/]]<repo>"
 }
 
 if ! HOST_ORG_REPO="$(echo "$1" | grep -Eo '^[^/]+/[^/]+/[^/]+/?$')"; then
 	if ! ORG_REPO="$(echo "$1" | grep -Eo '^[^/]+/[^/]+/?$')"; then	
 		if ! REPO="$(echo "$1" | grep -Eo '^[^/]+/?$')"; then
-			echo "Unable to parse repo path."
+			echo "Unable to parse repo path '$REPO_EXPRESSION'"
 			exit 1
 		else
 			HOST_ORG_REPO="$DEFAULT_HOST/$DEFAULT_ORG/$REPO"
@@ -76,24 +80,6 @@ debug "Got valid repo: REPO=$REPO"
 
 DIR="$SRC_BASEDIR/$REPO"
 
-if $NEW_REPO; then
-	debug "Creating new repo."
-	mkdir -p "$DIR"
-	cd "$DIR" || die "Unable to cd to $DIR"
-	git init
-	git remote add origin "https://$HOST_ORG_REPO"
-	echo "# $REPO" > README.md
-	git add README.md
-	git commit -m "initial commit"
-	BRANCH="$(git rev-parse --abbrev-ref HEAD)"
-	REMOTE="origin"
-	gh repo create "$(basename "$PWD")" --private --source=. --remote="$REMOTE"
-	git push "$REMOTE" "$BRANCH"
-	URL="$(gh repo view --json url | jq -r .url)"
-	log "New repo created at $URL"
-	sleep 1
-fi
-
 debug "Looking in: $DIR"
 
 [ ! -d "$DIR" ] || {
@@ -104,6 +90,25 @@ debug "Looking in: $DIR"
 	echo "$DIR"
 	exit 0
 }
+
+if $NEW_REPO; then
+	debug "Creating new repo."
+	mkdir -p "$DIR"
+	cd "$DIR" || die "Unable to cd to $DIR"
+	git init
+	#git remote add origin "https://$HOST_ORG_REPO"
+	echo "# $REPO" > README.md
+	git add README.md
+	git commit -m "initial commit"
+	BRANCH="$(git rev-parse --abbrev-ref HEAD)"
+	REMOTE="origin"
+	gh repo create "$ORG_REPO" --private --source=. --remote="$REMOTE"
+	git push -u "$REMOTE" "$BRANCH"
+	URL="$(gh repo view --json url | jq -r .url)"
+	log "New repo created at $URL"
+	sleep 1
+	exit 0
+fi
 
 debug "$DIR does not exist, creating base dir."
 mkdir -p "$(dirname "$DIR")"
