wt: switch opens wt in new tmux window

diff --git a/bin/wt b/bin/wt
--- a/bin/wt
+++ b/bin/wt
@@ -46,9 +46,7 @@ parsearg() {
 	}
 }
 array_is_empty() { [[ -z "${!1-}" ]]; }
-array_len() {
-	echo "${#@}"
-}
+array_len() { echo "${#@}"; }
 
 foreach() {
 	local action="$1" maxlen=0 len=0
@@ -180,7 +178,8 @@ wt.new+config() {
 }
 branch_exists() { git show-ref --verify --quiet "refs/heads/$1"; }
 remote_branch_ref() { git show-ref --verify --quiet "refs/remotes/$1"; }
-main_wt_root() { git -C "$(git worktree list | head -n1 | cut -d' ' -f1)" rev-parse --show-toplevel; }
+get_main_wt_root() { git -C "$(git worktree list | head -n1 | cut -d' ' -f1)" rev-parse --show-toplevel; }
+get_repo_name() { dirname "$(get_main_wt_root)"; }
 
 wt.rm() {
 	desc "$@" <<-EOF || return 0
@@ -207,8 +206,9 @@ rm_wt_dir() {
 	[[ -d "$DIR" ]] || die "Directory '%s' does not exist." "$DIR"
 	git worktree remove "$DIR"
 }
-get_wt_path() { echo "$(get_wt_base_dir)/${1:?}"; }
-get_wt_base_dir() { echo "$(main_wt_root)/.gitworktrees" || die "Not in a git repository."; }
+get_wt_path() { [[ "$1" == "main" ]] && get_main_wt_root && return $? || echo "$(get_wt_base_dir)/$1"; }
+get_existent_wt_path() ({ DIR="$(get_wt_path "$1")" && [[ -d "$DIR" ]] && echo "$DIR" && return 0; } || die "Worktree '%s' does not exist." "$1")
+get_wt_base_dir() { echo "$(get_main_wt_root)/.gitworktrees" || die "Not in a git repository."; }
 ensure_wt_base_dir() {
 	DIR="$(get_wt_base_dir)" && mkdir -p "$DIR" && echo "*" >"$DIR/.gitignore"
 }
@@ -242,6 +242,33 @@ wt.replace() {
 	get_wt_path "$BRANCH"
 }
 
+is_terminal() { [[ -t 1 ]]; }
+is_tmux() { [[ -n "${TMUX:-}" ]]; }
+
+open_tmux_window_or_print_dir() {
+	local DIR="$1" NAME="$2"
+	is_terminal && is_tmux && {
+		open_tmux_window "$1" "$2"
+		return 0
+	}
+	echo "$2"
+}
+
+open_tmux_window() {
+	# TODO: See if there's already a tmux window open for this worktree, if so switch
+	# to that window rather than opening a new one.
+	local DIR="$1"
+	local NAME="$2"
+	echo "Opening in new tmux window..."
+	tmux new-window -a -c "$DIR" -n "$(basename "$DIR")"\; \
+		send-keys \
+		"clear && " \
+		"git log -n3 && echo && " \
+		"git status && echo && " \
+		"git -c color.branch=always branch | sort | tac | head -n10" \
+		Enter
+}
+
 wt.co() {
 	desc "$@" <<-EOF || return 0
 		Check out a branch into a new worktree.
@@ -271,7 +298,9 @@ wt.co() {
 	get_wt_path "$BRANCH"
 }
 
-co_wt_dir() {
+# new_wt creates a new worktree directory and checks out the branch into it.
+# It fails if the worktree directory already exists.
+new_wt() {
 	local BRANCH="$1" BASE="$2" DIR
 	create_wt_dir "$BRANCH" || die
 
@@ -298,7 +327,7 @@ co_wt_dir() {
 }
 
 names() {
-	prefix="$(main_wt_root)/.gitworktrees/"
+	prefix="$(get_main_wt_root)/.gitworktrees/"
 	echo "main"
 	git worktree list | cut -d' ' -f1 | tail -n+2 | sed -E "s|$prefix||"
 }
@@ -321,24 +350,24 @@ wt.main() {
 	desc "$@" <<-EOF || return 0
 		Show the root of the main worktree.
 	EOF
-	main_wt_root
+	get_main_wt_root
 }
 
 wt.switch() {
 	desc "$@" <<-EOF || return 0
-		Print the root of the worktree named NAME.
+		Switch to a worktree, open a new tmux window there if possible.
+		Otherwise just print the wt path.
 
 		args: NAME
 
 		The special name "main" means the main worktree.
 
 		TODO: Implement this as an installable function to actually cd to the worktree.
-		TODO: Consider integrating with tmux like the 'src' command.
 	EOF
-	[[ "$NAME" == "main" ]] && main_wt_root && return 0
-	prefix="$(main_wt_root)/.gitworktrees"
-	dir="$prefix/$NAME"
-	[[ -d "$dir" ]] || die "Worktree '%s' does not exist, options are:\n%s" "$NAME" "$(names)"
-	echo "$dir"
+	local DIR
+	DIR="$(get_wt_path "$NAME")" || die
+	[[ -d "$DIR" ]] || die "Worktree '%s' does not exist, options are:\n%s" "$NAME" "$(names)"
+	WINDOW_NAME="$(get_repo_name)/$NAME"
+	open_tmux_window_or_print_dir "$DIR" "$WINDOW_NAME"
 
 }
